### ISSUE TITLE
Custom frame format idea

### ISSUE THREAD

**Issue by Kabron287** [hyOzd/serialplot#12]
Hi, there.
I guess that Custom Frame fomat description could be improved in the following way:
Frame Start - no change
Packed Data Structure as in **printf** format definitions.
E.g. : %f, %d, %u etc.
This will allow to mix different data types in one packet.
Endianness - no change
Checksum: - no change

Thanks in advance,
Vladimir

**Comment by hyOzd** [comment]
I plan to keep existing formats simple at the moment. Maybe we can implement a _scriptable frame format_ in the future.
