### ISSUE TITLE
featurerequest: different color for minor and mayor grid lines

### ISSUE THREAD

**Issue by s-light** [hyOzd/serialplot#21]
currently there is no difference between the main grid lines and the minor grid lines.
if the minor grid lines are a little bit darker then the mayor it is easier to see where a point is..

**Comment by hyOzd** [comment]
Added a slight difference between the line colors. [b7f4b6a](https://github.com/hyOzd/serialplot/commit/b7f4b6a1818490766e6afaca42fa005f2e15c28e)

Ideally in the future colors would be user configurable.
