### ISSUE TITLE
featurerequest: keyboard shortcuts do send commands

### ISSUE THREAD

**Issue by chrisemb** [hyOzd/serialplot#24]
I really like SerialPlot.

It would be great if it was possible to send commands also via keyboard shortcuts because this is faster than using the mouse for clicking the buttons in the Commands-tab or (if another tab is selected) selecting them in the Commands menu. 
For me, it would be sufficient if the first 12 commands were mapped to the function keys F1 to F12 respectively.

**Comment by hyOzd** [comment]
Implemented as you described.

5393747e73eb14b5cde0841aabcf495e4324746c
