### ISSUE TITLE
Maybe try to imitate and/or improve ESPlot?

### ISSUE THREAD

**Issue by VictorTagayun** [hyOzd/serialplot#25]
I haven't tried this software yet.
Maybe you may have some ideas to integrate from ESPlot.
[https://gitlab.com/esplot/esplot-computer-software](https://gitlab.com/esplot/esplot-computer-software) / [https://www.uni-saarland.de/en/chair/nienhaus/esplot-software.html](https://www.uni-saarland.de/en/chair/nienhaus/esplot-software.html)
Or you can add ESPlot in your repo and try to improve on it.

**Comment by hyOzd** [comment]
@VictorTagayun Thanks for the heads up. I will check it out. I think ESPlot runs more like a oscilloscope. SerialPlot is more like general purpose plotter. For my use cases, I prefer how serialplot works at the moment. A special mode for oscilloscope like operation could be added.
