### ISSUE TITLE
ppa error

### ISSUE THREAD

**Issue by dzbyr** [hyOzd/serialplot#3]
How can I fix 
$ sudo add-apt-repository ppa:hyozd/serialplot
Cannot add PPA: ''This PPA does not support bionic''.

**Comment by hyOzd** [comment]
ppa hasn't been updated for a long time. I recommend building from the bitbucket souces or download the appimage forom bitbucket

https://bitbucket.org/hyOzd/serialplot
https://bitbucket.org/hyOzd/serialplot/downloads/
