### ISSUE TITLE
Project is no longer available on bitbucket

### ISSUE THREAD

**Issue by fdila** [hyOzd/serialplot#4]
"Repository unavailable
Bitbucket no longer supports Mercurial repositories."

Is the version on github updated? Could you put the appimage files in the "releases" section here? Thanks!

**Comment by hyOzd** [comment]
Up to date version is on https://hg.sr.ht/~hyozd/serialplot/

I'm sorry I couldn't keep up the git version of the repository (original is mercurial).

I will put the new links to appimage files on hackaday page https://hackaday.io/project/5334-serialplot-realtime-plotting-software

**Comment by buaabyl** [comment]
Could you update this link in the project setting? It may help others to find the new link :)

![old_link](https://user-images.githubusercontent.com/1212230/92424972-6771a900-f1b8-11ea-8d10-23e16892949e.png)

**Comment by prashant3285** [comment]
Windows download link alternative.

http://www.armfly.com/armbbs/bbs/97520/serialplot-0.10.0-win32.exe
http://www.armfly.com/armbbs/bbs/97520/serialplot-0.10.0-win64.exe

for time being it can be downloaded from here
Source:  http://armbbs.cn/forum.php?mod=viewthread&tid=97520&extra=page%3D1

**Comment by hyOzd** [comment]
I've published a new release and put the links  on the hackaday.io page, please check this page in the future for new releases:

https://hackaday.io/project/5334-serialplot-realtime-plotting-software

Here are the links:
https://serialplot.ozderya.net/downloads/serialplot-v0.11.0-x86_64.AppImage
https://serialplot.ozderya.net/downloads/serialplot-0.11.0-win32.exe
