### ISSUE TITLE
featurerequest: Change Line Thickness of Plot

### ISSUE THREAD

**Issue by AGenews** [hyOzd/serialplot#42]
First, thank you for developing serialplot. It is a great tool I use for example to teach courses in electronics for biologists. For screen capture the line width is often to thin, and being able to change the line width would greatly aid visibility for the students.

Thank You!
Best,
agenews

**Comment by hyOzd** [comment]
Implemented with https://github.com/hyOzd/serialplot/commit/d1301165d39541f60f8c6d71ca6b2da443129edc
