### ISSUE TITLE
Need to support BAUD rates of 460800 and 230400..

### ISSUE THREAD

**Issue by TurboStew** [hyOzd/serialplot#59]
Modern USB serial ports are running this fast.

Thanks,
Kent

**Comment by hyOzd** [comment]
You can enter any baud rate you want into the baud rate selection box. Are you having trouble with that?

**Comment by TurboStew** [comment]
Sorry, didn't realize I could type in the Baud Rate box.   Works great, Thank You!

**Comment by hyOzd** [comment]
No problem.
