### ISSUE TITLE
Bug？：Custom Frame select checksum 

### ISSUE THREAD

**Issue by zhgw90** [hyOzd/serialplot#67]
Custom Frame select checksum ，checksum  can't pass。

![1111](https://github.com/user-attachments/assets/bd8e3d63-e306-4172-8b2f-b8af486ec9e1)

**Comment by hyOzd** [comment]
I don't see a bug here. Can you elaborate?

**Comment by zhgw90** [comment]
sorry, i thougth wrong。I included the packge head in my calculations
