### ISSUE TITLE
SAVING DATA TO A SEPARATE FILE

### ISSUE THREAD

**Issue by marco-pola** [hyOzd/serialplot#9]
Hello!
Thank you for your very nice and intuitive program. I am relatively new in programming and handling data from serial ports.
I was wondering if there is the possibility to save only some of the incoming data in a txt file different from the log file of the recording or tag them in order to extract them later from the full recording log.
For example:
I am getting from my serial port the values: 1, 2, 3, 4, 5, 5, 5, 5. I see that the value 5 is stable and I would like to save or tag it. Afterwards, my logging continues and after a while I get another stable value that I would like to save/tag and so on. 
Thank you for your help.
Marco

**Comment by hyOzd** [comment]
I think you mean like a single data point, not a portion of data? This could be added with the markers feature. But it is not going to be implemented soon.

**Comment by marco-pola** [comment]
Yes, I meant a single data point. Adding a marker to that point could be a perfect solution, because then I can select only the marked points using Excel for example. 
However, also a portion of the dataset could work (i.e., I could save only the data when I see that a stable value is reached). Do you have a solution in mind for that?
Eventually, for the marker option, when do you think it could be implemented?
Thanks
Marco

**Comment by hyOzd** [comment]
@marco-pola Unfortunately not soon. For this I will have to implement X-axis feature. Currently serialplot doesn't have a notion of X axis. But it is difficult to implement it at this point without breaking existing features/optimizations. So it will take a while. Please don't expect anything.

It is not a pretty solution but; you could start a recording, then stop the recording when you see the value you are interested. Then immediately re-start the recording. With 'auto increment file name' option this will create a new recording with a new file name. With this approach you will have files that contain the data you are interested at the end of the file. Files can be a little too big depending on your use case. That's the only solution I can think of at the moment.
